name: CI Checks

on:
    push:

    
    pull_request:
        branches:
            - main  
            

jobs: 
    front-end:
        runs-on: ubuntu-latest     
        
        defaults:
            run:
                working-directory: front-end
          
        steps:
            - uses: actions/checkout@v4
            
            - uses: actions/setup-node@v4
              with:
                node-version: 26
                cache: npm
                cache-dependency-path: front-end/package-lock.json

            - name: Install dependencies
              run: npm ci

            - name: Run ESLintgit
              run: npm run lint

            - name: Build frontend
              run: npm run build
            
    back-end:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: back-end
             
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}        

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                node-version: 26
                cache: npm
                cache-dependency-path: back-end/package-lock.json

            - name: Install dependencies
              run: npm ci

            - name: Validate Prisma schema
              run: npx prisma validate

            - name: Build backend
              run: npm run build
               